// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const HoneyTokensSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  type: z.string(),
  status: z.string().default("active"),
  projectId: z.string(),
  folderId: z.string().uuid(),
  connectionId: z.string().uuid(),
  encryptedCredentials: zodBuffer,
  secretsMapping: z.unknown(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type THoneyTokens = z.infer<typeof HoneyTokensSchema>;
export type THoneyTokensInsert = Omit<z.input<typeof HoneyTokensSchema>, TImmutableDBKeys>;
export type THoneyTokensUpdate = Partial<Omit<z.input<typeof HoneyTokensSchema>, TImmutableDBKeys>>;
